source/accounts/urls.py
from django.urls import path
from accounts.views import RegisterView, UserChangePasswordView, UserDetailView, UserChangeView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('change/',  UserChangeView.as_view(), name='change'),
    path('user/change/password/', UserChangePasswordView.as_view(), name='user_change_password'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')

    def __str__(self):
        return f"{self.user.username} 's Profile"

    class Meta:
        db_table = 'profile'
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'
        permissions = [('user_list_view', 'Просмотр всех пользователей'), ]

source/accounts/views.py
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from django.views.generic.list import MultipleObjectMixin
from django.contrib.auth import login, get_user_model
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from .form import MyUserCreationForm, UserChangeForm
from .models import Profile


class RegisterView(CreateView):
    model = get_user_model()
    template_name = 'user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:project:index')
        return next_url


class UserDetailView(LoginRequiredMixin, DetailView, MultipleObjectMixin):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        ads = self.get_object().ads.all()
        for i in ads:
            if i.user == self.request.user:
                ads = self.get_object().ads.all().exclude(status='For removal')
            else:
                ads = self.get_object().ads.all().filter(status='published')
        return super().get_context_data(object_list=ads, **kwargs)

class UserChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.get_object().pk})


class UserChangePasswordView(PasswordChangeView):
    template_name = 'user_change_password.html'

    def get_success_url(self):
        return reverse('accounts:user_view', kwargs={'pk': self.request.user.pk})

source/accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}

    <h1 style="text-align: center">Login</h1>
    <form action="" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="text-danger">The username or password is not correct. Retype your username and password.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Username:</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Password:</label>
            <input type="password" name="password" id="password">
        </div>
        <button type="submit">Login</button>
    </form>
{% endblock %}

source/accounts/templates/user_change.html
{% extends 'base.html' %}
{% block content %}
    <h1>Поменять личные данные</h1>

    <form action="" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text="Update" %}

    </form>
{% endblock %}

source/accounts/templates/user_change_password.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mx-4">Change your Password</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% include 'partial/form.html' with button_text='change'%}
</form></br>
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}

{% block content %}
<h1>Sign in</h1>
<form action = "" method="post">
    {% include 'partial/form.html' with button_text='Sign in'%}
</form></br>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block nav %}
    {% if user_obj.pk == request.user.pk %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:change' %}">Редактировать </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:user_change_password' %}">Смена пароля</a>
    </li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>

    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Имя пользователя: {{ user_obj.username }}</h5>
                    <p class="card-text">Имя: {{ user_obj.first_name }}</p>
                    <p class="card-text">Фамилия: {{ user_obj.last_name }}</p>
                    <p class="card-text">Почта: {{ user_obj.email }}</p>
                </div>
            </div>
        </div>
    </div>

    {% include 'partial/ad_list_partial.html' with ads=object_list %}
{% endblock %}

source/accounts/templates/user_view.html
{% extends 'base.html' %}

{% block content %}
    <h1>User personal page {{ user_obj.get_full_name|default:user_obj.username }}</h1>
    <div class="card mb-3">
        <div class="row g-0">
            {% if user_obj.profile.avatar %}
                <div class="col-md-3">
                    <img src="{{ user_obj.profile.avatar.url }}" class="img-fluid rounded-start w-75">
                </div>
            {% endif %}
            {% if not user_obj.profile.avatar %}
            <div class="col-md-16">
            {% else %}
            <div class="col-md-9">
            {% endif %}
                <div class="card-body">
                     <div class="d-flex">
                         <h1>Summary: {{ user_obj }}</h1>
                         {% if user_obj.pk == request.user.pk %}
                         <div class="ms-auto">
                         <a href="{% url 'accounts:user_update_profile' %}" class= "btn btn-primary "><i class="bi bi-pencil mx-2" style="font-size:25px"></i></a>
                         <a href="{% url 'accounts:user_change_password' %}" class= "btn btn-primary "><i class="bi bi-shield-fill-check mx-2" style="font-size:25px"></i></a>
                         </div>
                         {% endif %}
                    </div>
                    <p class="card-text">FirstName: {{ user_obj.first_name }}</p>
                    <p class="card-text">LastName: {{ user_obj.last_name }}</p>
                    <p class="card-text">Email: {{ user_obj.email }}</p>
                    <p class="card-text">description: {{ user_obj.profile.description }}</p>
                    {% if user_obj.profile.git %}
                    <p class="card-text" style="text-decoration: none">Github: <a href="{{ user_obj.profile.git }}">{{ user_obj.profile.git }}</a></p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% include 'partial/project_list_partial.html' with projects=object_list %}

{% endblock %}