source/accounts/urls.py
from django.urls import path
from accounts.views import RegisterView, UserChangePasswordView, UserDetailView, UserChangeView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', RegisterView.as_view(), name='create'),
    path('change/',  UserChangeView.as_view(), name='change'),
    path('user/change/password/', UserChangePasswordView.as_view(), name='user_change_password'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include
from .views import AdIndexViews, AdView, AdCreateView, AdUpdateView, AdDeleteView, AdCommentCreateView, CommentDeleteView, AdAll, AdDobro, AdOtklon
app_name = 'webapp'

AddUrl = [
    path('all/', AdAll.as_view(), name='ad_all'),
    path('dobro/<int:pk>/', AdDobro.as_view(), name='dobro'),
    path('otklon/<int:pk>/', AdOtklon.as_view(), name='otklon'),
    path('<int:pk>/', AdView.as_view(), name='ad_view'),
    path('update/<int:pk>/', AdUpdateView.as_view(), name='ad_update'),
    path('create', AdCreateView.as_view(), name='ad_create'),
    path('delete/<int:pk>/', AdDeleteView.as_view(), name='ad_delete'),
]

CommentUrl = [
    path('<int:pk>/comment/add/', AdCommentCreateView.as_view(), name='ad_comment_add'),
    path('<int:pk>/comment/delete/', CommentDeleteView.as_view(), name='comment_delete'),

]

urlpatterns = [
    path('', AdIndexViews.as_view(), name='ad_index'),
    path('ad/', include(AddUrl)),
    path('comment/', include(CommentUrl)),

]

source/webapp/models.py
from django.db import models

# Create your models here.
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

CATEGORY_CHOICES = [('on moderate', 'На модерацию'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('For removal', 'На удаление')]

# Create your models here.


class Ad(models.Model):
    photo = models.ImageField(blank=True, null=True, upload_to='product_photo', verbose_name="Аватар")
    title = models.CharField(max_length=30, verbose_name="Заголовок")
    description = models.TextField(max_length=3000, verbose_name="Описание", null=True, blank=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1, related_name='ads',
                               verbose_name="Автор")
    category = models.ForeignKey('webapp.Category', on_delete=models.PROTECT, related_name='categories')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    status = models.CharField(max_length=30, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0][0],
                                verbose_name="Категория")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата начала")
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата обновление")
    published_at = models.DateTimeField(null=True, blank=True, verbose_name="Дата публикации")

    def get_absolute_url(self):
        return reverse('webapp:ad_view', kwargs={'pk': self.pk})

    class Meta:
        permissions = [('is_staff', 'Модератор'), ]



class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name="Статус")

    def __str__(self):
        return f'{self.name}'


class Comment(models.Model):
    text = models.TextField(max_length=400, verbose_name='Комментарий')
    ad = models.ForeignKey('webapp.Ad', on_delete=models.CASCADE, related_name='comments',
                                verbose_name="объявление")
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1, related_name='comments',
                               verbose_name="Автор")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")


    def __str__(self):
        return f'{self.pk}. {self.text[:20]}'

source/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets

from webapp.models import Ad, Comment


class AdForm(forms.ModelForm):
    class Meta:
        model = Ad
        fields = ['photo', 'title', 'description', 'category', 'price']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }
        error_messages = {
            'content': {
                'required': 'Поле должно быть заполнено'
            }
        }


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label='Найти', widget=widgets.TextInput(attrs={'class': "form-control w-25"}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

source/webapp/views/ad_views.py
from urllib.parse import urlencode

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from webapp.models import Ad
from webapp.forms import AdForm, SimpleSearchForm
from django.http import JsonResponse, HttpResponseRedirect, HttpResponseNotFound, HttpResponse

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View


class AdDobro(PermissionRequiredMixin, View):
    permission_required = 'webapp.is_staff'

    def get(self, *args, **kwargs):
        ad = get_object_or_404(Ad, pk=self.kwargs.get('pk'))
        ad.status = 'rejected'
        ad.save()
        data = {
            'data': ad.pk
        }
        response = JsonResponse(data)
        return response


class AdOtklon(PermissionRequiredMixin, View):
    permission_required = 'webapp.is_staff'

    def get(self, *args, **kwargs):
        ad = get_object_or_404(Ad, pk=self.kwargs.get('pk'))
        ad.status = 'rejected'
        ad.save()
        data = {
            'data': ad.pk
        }
        response = JsonResponse(data)
        return response


class AdAll(PermissionRequiredMixin, ListView):
    template_name = 'ad/ad_all.html'
    context_object_name = 'ads'
    model = Ad
    ordering = ('-created_at',)
    paginate_by = 3
    permission_required = 'webapp.is_staff'

    def get_queryset(self):
        queryset = Ad.objects.filter(status='on moderate')
        if self.search_value:
            queryset = queryset.filter(
                Q(title__icontains=self.search_value) | Q(description__icontains=self.search_value)).filter(
                status='on moderate')
        return queryset

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context

class AdIndexViews(ListView):
    template_name = 'ad/index.html'
    context_object_name = 'ads'
    model = Ad
    ordering = ('-created_at',)
    paginate_by = 3

    def get_queryset(self):
        queryset = Ad.objects.filter(status='published')
        if self.search_value:
            queryset = queryset.filter(Q(title__icontains=self.search_value) | Q(description__icontains=self.search_value)).filter(status='published')
        return queryset

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class AdView(DetailView):
    template_name = 'ad/ad_view.html'
    context_object_name = 'ad'
    model = Ad

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ad = self.object
        comments = ad.comments.order_by('-created_at')
        context['comments'] = comments
        return context


class AdCreateView(LoginRequiredMixin, CreateView):
    template_name = "ad/ad_create.html"
    model = Ad
    form_class = AdForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class AdUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = "ad/ad_update.html"
    model = Ad
    form_class = AdForm

    def form_valid(self, form):
        if self.get_object().status == 'rejected':
            return HttpResponseNotFound('<h1>you can not update rejected ad only delete</h1>')
        else:
            form.instance.status = 'on moderate'
            return super().form_valid(form)

    def has_permission(self):
        return self.get_object().user == self.request.user


class AdDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'ad/ad_delete.html'
    model = Ad
    success_url = reverse_lazy('webapp:ad_index')


    def has_permission(self):
        return self.get_object().user == self.request.user

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.status = 'For removal'
        self.object.save()
        return redirect('webapp:ad_index')

source/webapp/views/comment_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import CommentForm
from webapp.models import Comment, Ad


class AdCommentCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'comment/create.html'
    model = Comment
    form_class = CommentForm

    def has_permission(self):
        ad = get_object_or_404(Ad, pk=self.kwargs.get('pk'))
        return ad.user != self.request.user

    def get_success_url(self):
        return reverse('webapp:ad_view', kwargs={'pk': self.object.ad.pk})

    def form_valid(self, form):
        ad = get_object_or_404(Ad, pk=self.kwargs.get('pk'))
        form.instance.ad = ad
        form.instance.author = self.request.user
        return super().form_valid(form)


class CommentDeleteView(PermissionRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment

    def has_permission(self):
        ad = get_object_or_404(Ad, pk=self.kwargs.get('pk'))
        return ad.user == self.request.user

    def test_func(self):
        return self.request.user.has_perm('webapp.delete_comment') or self.get_object().author == self.request.user

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('webapp:ad_view', kwargs={'pk': self.object.ad.pk })

source/webapp/templates/ad/ad_all.html
{% extends 'base.html' %}

{% load static %}

{% block nav %}
{% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:ad_create' %}">Create Ad</a>
        </li>
{% endif %}
{% endblock %}
<style>
    .alert{
        position: absolute;
        right: 0px;
        width: 300px;
        border: 3px solid #73AD21;
        padding: 10px;
    }
    .button{
        position: absolute;
        right: 0px;
    }
</style>
{% block content %}
    {% include 'partial/search.html' %}

    <h1>Ads</h1>
    <div class="row">
        {% for ad in ads %}
            <div class="col-4 my-3">
                <div class="card">
                    <div class="card-body">
                        {% if ad.photo %}
                        <img src="{{ ad.photo.url }}" class="img-fluid rounded-start w-75">
                        {% endif %}
                        <h5 class="card-title">Заголовок: {{ ad.title }} </h5>
                        <p class="card-text">Автор: <a href="{% url 'accounts:detail' ad.user.pk %}">{{ ad.user }}</a></p>
                        <p class="card-text">Цена: {{ ad.price }}</p>
                        <a href="{{ ad.get_absolute_url }}" class="btn btn-primary">Подробнее...</a>
                        <button id="button" class="btn btn-primary" data-index-link="{% url 'webapp:dobro' ad.pk %}">Одобрить</button>
                        <button id="button" class="btn btn-primary" data-index-link="{% url 'webapp:otklon' ad.pk %}">Отклонить</button>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div id="change"></div>
 {% if is_paginated %}
        {% include 'partial/pagination.html' %}
{% endif %}


{% endblock %}

source/webapp/templates/ad/ad_create.html
{% extends 'base.html' %}
{% block content %}
    <h1>Create Ad</h1>

    <form action="" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text="Create" %}
    </form>
{% endblock %}

source/webapp/templates/ad/ad_delete.html
{% extends "base.html" %}
{% block title %}Delete Ad{% endblock %}


{% block content %}
    <form method="POST" action="" class="text-center" style="color: black">
        <h1>Are you sure want to delete ad </h1>
        <h2>Summary: {{ ad.name }}</h2>
        <p>Description: {{ ad.description }}</p>
        {% csrf_token %}
        <input class="btn" style="border:solid 2px black" type="submit" value="Yes" >
        <a style="border:solid 2px black" href="{% url "webapp:ad_view" ad.pk %}" class="btn rounded text-decoration-none link-dark">No</a>
    </form>
{% endblock %}

source/webapp/templates/ad/ad_update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Update Ad</h1>

    <form action="" method="post">
        {% include 'partial/form.html' with button_text="Update" %}
    </form>
{% endblock %}

source/webapp/templates/ad/ad_view.html
{% extends 'base.html' %}
{% block nav %}
{% if request.user.is_authenticated %}
        {% if request.user == ad.user %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:ad_update' ad.pk %}">Update Ad</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:ad_delete' ad.pk %}">Delete Ad</a>
        </li>
        {% endif %}

        {% if request.user != ad.user %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:ad_comment_add' ad.pk %}">Add comment</a>
        </li>
        {% endif %}
{% endif %}
{% endblock %}
{% block content %}
    <div class="card mb-3">
        <div class="row g-0">
                <div class="col-md-4">
                     {% if ad.photo %}
                        <img src="{{ ad.photo.url }}" class="img-fluid rounded-start w-75">
                     {% endif %}
                </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Заголовок: {{ ad.title }} </h5>
                    <p class="card-text">Автор: <a href="{% url 'accounts:detail' ad.user.pk %}">{{ ad.user.pk }}</a></p>
                    <p class="card-text">Описание: {{ ad.description }}</p>
                    <p class="card-text">Категория: {{ ad.category }}</p>
                    <p class="card-text">Дата создание: {{ ad.created_at }}</p>
                    <p class="card-text">Цена: {{ ad.price }}</p>
                </div>
            </div>
        </div>
    </div>
 <h3 class="ms-3">Comments:</h3>
    <div class="row">
        {% for comment in comments %}
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">Автор: <a href="{% url 'accounts:detail' comment.author.pk %}">{{  comment.author.username }}</a></p>
                        <p class="card-text">Комментарий: {{ comment.text }}</p>
                        <p class="card-text">Дата: {{ comment.created_at }}</p>

                        {% if comment.author == request.user %}
                                <a href="{% url 'webapp:comment_delete' comment.pk %}"
                                   class="btn btn-danger px-5">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Комментариев нет</p>
        {% endfor %}
    </div>
{% endblock %}

source/webapp/templates/ad/index.html
{% extends 'base.html' %}


{% block nav %}
{% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:ad_create' %}">Create Ad</a>
        </li>
{% endif %}
{% endblock %}

{% block content %}

    {% include 'partial/ad_list_partial.html' %}
{% endblock %}